[package]
name = "basalt-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
protoxene = { git = "https://github.com/basalt-rs/protoxene.git", features = [
    "server",
], rev = "2c9f2d8" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
