[package]
name = "basalt-server"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio-native-tls"] }
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
packet = { git = "https://github.com/basalt-rs/packet.git", rev = "45dd8cd" }
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
directories = "6.0.0"
rand = "0.8.5"
axum = { version = "0.8.1", features = ["macros"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
utoipa-axum = { version = "0.2.0", features = ["debug"] }
utoipa = { version = "5.3.1", features = ["debug"] }

[dev-dependencies]
async-tempfile = "0.6.0"
