permissions:
    contents: read
    packages: write

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

name: publish main image

jobs:
    build:
        strategy:
            matrix:
                arch: [amd64, arm64]
                include:
                    - arch: amd64
                      runner: ubuntu-24.04
                      platform: linux/amd64
                    - arch: arm64
                      runner: ubuntu-24.04-arm
                      platform: linux/arm64
        runs-on: ${{ matrix.runner }}
        steps:
            - uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build & push main (${{ matrix.arch }})
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./containers/Dockerfile
                  platforms: ${{ matrix.platform }}
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/basalt-server:main-${{ matrix.arch }}

    manifest:
        needs: build
        runs-on: ubuntu-24.04
        steps:
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create and push multi-arch manifest for main
              run: |
                  docker buildx imagetools create \
                    -t ghcr.io/${{ github.repository_owner }}/basalt-server:main \
                    ghcr.io/${{ github.repository_owner }}/basalt-server:main-amd64 \
                    ghcr.io/${{ github.repository_owner }}/basalt-server:main-arm64
