name: spellcheck
on:
    pull_request:
jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: rojopolis/spellcheck-github-actions@0.48.0
              with:
                  source_files: README.md
                  task_name: Readme
              name: Spellcheck
